/* ALERT */
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

/* AUTH */
export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const UPDATE_MY_PASSWORD = 'UPDATE_MY_PASSWORD';
export const UPDATE_MY_EMAIL = 'UPDATE_MY_EMAIL';
export const SEND_FORGOTTEN_PASSWORD_EMAIL = 'SEND_FORGOTTEN_PASSWORD_EMAIL';
export const TRYAGAIN_SEND_FORGOTTEN_PASSWORD_EMAIL = 'TRYAGAIN_SEND_FORGOTTEN_PASSWORD_EMAIL';
export const RESET_PASSWORD = 'RESET_PASSWORD';

/* USER */
// for me page //
export const USER_DATA = 'USER_DATA';

/* Stats For Category */
export const STATS_PRODUCTS = 'STATS_PRODUCTS';
export const STATS_SUPPLIERS = 'STATS_SUPPLIERS'

/* PRODUCTS */
// utils //
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT';
export const UPDATE_VIEWS = 'UPDATE_VIEWS';

export const MY_POST = 'MY_POST';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const GET_ONE_EDIT_PRODUCT = 'GET_ONE_EDIT_PRODUCT'
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_SIMILAR_PRODUCT = 'GET_SIMILAR_PRODUCT';
export const UPDATE_FEATURES = 'UPDATE_FEATURES';
export const RELIST = 'RELIST';
export const USER_POST = 'USER_POST';

// for Image upload using firebase //
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';

// for category //
export const SEARCH_BAR_FOR_PRODUCTS = 'SEARCH_BAR_FOR_PRODUCTS';
export const FILTER = 'FILTER';

/* REVIEWS */
export const MY_REVIEW = 'MY_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';

/* Followings */
export const GET_FOLLOWS = 'GET_FOLLOWS';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';
export const GET_LATEST_FOLLOW_PRODUCT = 'GET_LATEST_FOLLOW_PRODUCT';
export const SEARCH_BAR_FOR_SHOPNAME = 'SEARCH_BAR_FOR_SHOPNAME';
export const DELETE_ALL_REVIEWS = 'DELETE_ALL_REVIEWS';
export const UPDATE_FOLLOWINGS = 'UPDATE_FOLLOWINGS';

/* Ticket */
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY' //note this is inside productActions
export const LENGTH_TICKET = 'LENGTH_TICKET';
export const GET_ALL_TICKET = 'GET_ALL_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const STATUS_TICKET = 'STATUS_TICKET';
export const BUYER_TICKET_HISTORY = 'BUYER_TICKET_HISTORY';
export const SELLER_TICKET_HISTORY = 'SELLER_TICKET_HISTORY';
export const TRUST_POINT = 'TRUST_POINT';
export const TICKET_TO_BIN = 'TICKET_TO_BIN';
export const GET_BUYER_TICKET_BIN = 'GET_BUYER_TICKET_BIN';
export const DELETE_BUYER_TICKET_BIN= 'DELETE_BUYER_TICKET_BIN';
export const GET_SELLER_TICKET_BIN = 'GET_SELLER_TICKET_BIN';
export const DELETE_SELLER_TICKET_BIN = 'DELETE_SELLER_TICKET_BIN';

/* Admin */
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_PRODUCT_DATA = 'GET_PRODUCT_DATA';
export const GET_USER_PRODUCTS_DATA = 'GET_USER_PRODUCTS_DATA';
export const DELETE_DATA = 'DELETE_DATA';
export const CREATE_USER = 'CREATE_USER';
export const GET_TICKET = 'GET_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const GET_SUGGESTION = 'GET_SUGGESTION';
export const GET_REPORTED_PRODUCTS = 'GET_REPORTED_PRODUCTS';
